# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e06e1e092394df2ee183a70e84458d427cc75c579e26ce634051472ef8a9163cec53603c104eb821fd76846b91a0436d7733d14ee8695d2437aea96f6cf00c0

test:
  secret_key_base: cafa17bad6ee6dedb34acd627240d754730f84f663c2c930f369b0d2afa979bf6fe0f1110da4a8a0b47efe8213b519e1b0911f09e677428e826502851fc70fc2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
